---
# RedHat/CentOS/Amazon Linux specific tasks

- name: Install Java (Amazon Corretto)
  yum:
    name:
      - java-{{ java_version }}-amazon-corretto
      - java-{{ java_version }}-amazon-corretto-devel
    state: present
  vars:
    java_version: "{{ java_version | default('17') }}"
  failed_when: false
  register: java_install_result

- name: Add Corretto repository if Java installation failed
  get_url:
    url: https://yum.corretto.aws/corretto.repo
    dest: /etc/yum.repos.d/corretto.repo
    mode: '0644'
  when: java_install_result is failed

- name: Retry Java installation after adding repository
  yum:
    name:
      - java-{{ java_version }}-amazon-corretto
      - java-{{ java_version }}-amazon-corretto-devel
    state: present
  vars:
    java_version: "{{ java_version | default('17') }}"
  when: java_install_result is failed

- name: Install Jenkins repository
  yum:
    name: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    state: present

- name: Import Jenkins GPG key
  rpm_key:
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    state: present

- name: Install Jenkins
  yum:
    name: "jenkins-{{ jenkins_version | default('2.414.3') }}"
    state: present
    update_cache: yes
  register: jenkins_install

- name: Start and enable Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes
  when: jenkins_install is succeeded

- name: Install additional packages
  yum:
    name:
      - git
      - unzip
      - curl
      - wget
      - jq
      - python3
      - python3-pip
    state: present



